name: Run tests on PR -> Ubuntu
on:
  pull_request:
    branches: ["main"]

jobs:
  utests:
    name: Run Unit tests - OS > Ubuntu Latest - Go 1.16
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Running Unit Tests
        run: make test